import React,{useEffect,useState} from 'react';
import {Alert,Box,Button,Dialog,DialogActions,DialogContent,DialogTitle,IconButton,Table,TableBody,TableCell,TableContainer,TableHead,TableRow,Tooltip,Typography} from '@mui/material';
import {EditOutlined,CancelOutlined,RefreshOutlined} from '@mui/icons-material';
import api,{errorMessage} from '../../api/client';
import PageHeader from '../../components/PageHeader';import MainCard from '../../components/MainCard';import StatusBadge from '../../components/StatusBadge';import BookingDialog from '../../components/BookingDialog';import {fmtDateTime} from '../../utils/date';
export default function MyBookingsPage(){const [rows,setRows]=useState([]);const [rooms,setRooms]=useState([]);const [edit,setEdit]=useState(null);const [cancel,setCancel]=useState(null);const [error,setError]=useState('');
 const load=async()=>{try{const [b,r]=await Promise.all([api.get('/bookings/mine'),api.get('/rooms')]);setRows(b.data);setRooms(r.data);setError('')}catch(e){setError(errorMessage(e))}};useEffect(()=>{load()},[]);
 const doCancel=async()=>{try{await api.patch(`/bookings/${cancel.id}/cancel`);setCancel(null);load()}catch(e){setError(errorMessage(e))}};
 return <><PageHeader title="My Bookings" subtitle="Track, edit or cancel your room requests." action={<Button startIcon={<RefreshOutlined/>} onClick={load}>Refresh</Button>}/>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}<MainCard><TableContainer><Table><TableHead><TableRow><TableCell align="center">No.</TableCell><TableCell>Meeting</TableCell><TableCell>Room</TableCell><TableCell>Start</TableCell><TableCell>End</TableCell><TableCell>People</TableCell><TableCell>Status</TableCell><TableCell>Admin note</TableCell><TableCell align="right">Actions</TableCell></TableRow></TableHead><TableBody>{rows.map((b,index)=><TableRow key={b.id} hover><TableCell align="center">{index+1}</TableCell><TableCell><Typography fontWeight={700}>{b.title}</Typography><Typography variant="caption" color="text.secondary">#{b.id}</Typography></TableCell><TableCell>{b.room.code} - {b.room.name}</TableCell><TableCell>{fmtDateTime(b.startAt)}</TableCell><TableCell>{fmtDateTime(b.endAt)}</TableCell><TableCell>{b.attendeeCount}</TableCell><TableCell><StatusBadge status={b.status}/></TableCell><TableCell>{b.adminNote||'-'}</TableCell><TableCell align="right"><Tooltip title="Edit"><span><IconButton size="small" disabled={!['PENDING','APPROVED'].includes(b.status)||new Date(b.startAt)<=new Date()} onClick={()=>setEdit(b)}><EditOutlined fontSize="small"/></IconButton></span></Tooltip><Tooltip title="Cancel"><span><IconButton size="small" color="error" disabled={!['PENDING','APPROVED'].includes(b.status)||new Date(b.startAt)<=new Date()} onClick={()=>setCancel(b)}><CancelOutlined fontSize="small"/></IconButton></span></Tooltip></TableCell></TableRow>)}{rows.length===0&&<TableRow><TableCell colSpan={9} align="center" sx={{py:6,color:'text.secondary'}}>No bookings yet.</TableCell></TableRow>}</TableBody></Table></TableContainer></MainCard>
 <BookingDialog open={Boolean(edit)} onClose={()=>setEdit(null)} booking={edit} rooms={rooms} onSaved={load}/><Dialog open={Boolean(cancel)} onClose={()=>setCancel(null)}><DialogTitle>Cancel booking?</DialogTitle><DialogContent>Cancel <b>{cancel?.title}</b>? This action keeps the history but releases the room if it was approved.</DialogContent><DialogActions><Button onClick={()=>setCancel(null)}>Keep</Button><Button color="error" variant="contained" onClick={doCancel}>Cancel booking</Button></DialogActions></Dialog></>}
