import React,{useEffect,useState} from 'react';
import {Alert,Box,Card,CardContent,Grid,LinearProgress,Table,TableBody,TableCell,TableHead,TableRow,Typography} from '@mui/material';
import {MeetingRoomOutlined,PendingActionsOutlined,EventAvailableOutlined,UpcomingOutlined,PeopleAltOutlined} from '@mui/icons-material';
import dayjs from 'dayjs';
import api,{errorMessage} from '../../api/client';
import {useAuth} from '../../auth/AuthContext';
import PageHeader from '../../components/PageHeader';import MainCard from '../../components/MainCard';import StatusBadge from '../../components/StatusBadge';import {fmtDateTime} from '../../utils/date';
const cards=[['rooms','Rooms',<MeetingRoomOutlined/>],['pending','Pending approval',<PendingActionsOutlined/>],['approvedToday','Approved today',<EventAvailableOutlined/>],['myUpcoming','My upcoming',<UpcomingOutlined/>],['users','Users',<PeopleAltOutlined/>]];
export default function DashboardPage(){const {user,isAdmin}=useAuth();const [summary,setSummary]=useState(null);const [upcoming,setUpcoming]=useState([]);const [error,setError]=useState('');
 useEffect(()=>{(async()=>{try{const from=dayjs().format('YYYY-MM-DD'),to=dayjs().add(6,'day').format('YYYY-MM-DD');const [s,c]=await Promise.all([api.get('/dashboard/summary'),api.get('/bookings/calendar/range',{params:{from,to}})]);setSummary(s.data);setUpcoming(c.data.slice(0,8))}catch(e){setError(errorMessage(e))}})()},[]);
 return <><PageHeader title={`Welcome, ${user?.fullName}`} subtitle="Overview of room availability and booking activity."/>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}{!summary&&<LinearProgress sx={{mb:3}}/>}<Grid container spacing={2.2} sx={{mb:3}}>{cards.filter(([k])=>isAdmin||k!=='users').map(([key,label,icon])=><Grid item xs={12} sm={6} lg={isAdmin?2.4:3} key={key}><Card><CardContent><Box sx={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><Box><Typography color="text.secondary" fontSize={13}>{label}</Typography><Typography variant="h4" sx={{mt:.7}}>{summary?.[key]??'-'}</Typography></Box><Box sx={{width:46,height:46,borderRadius:2,bgcolor:'#edf5ff',color:'primary.main',display:'grid',placeItems:'center'}}>{icon}</Box></Box></CardContent></Card></Grid>)}</Grid>
 <MainCard title="Next 7 days"><Table><TableHead><TableRow><TableCell align="center">No.</TableCell><TableCell>Meeting</TableCell><TableCell>Room</TableCell><TableCell>Organizer</TableCell><TableCell>Time</TableCell><TableCell>Status</TableCell></TableRow></TableHead><TableBody>{upcoming.map((b,index)=><TableRow key={b.id}><TableCell align="center">{index+1}</TableCell><TableCell><Typography fontWeight={700}>{b.title}</Typography></TableCell><TableCell>{b.room.code} - {b.room.name}</TableCell><TableCell>{b.createdBy.fullName}</TableCell><TableCell>{fmtDateTime(b.startAt)}</TableCell><TableCell><StatusBadge status={b.status}/></TableCell></TableRow>)}{upcoming.length===0&&<TableRow><TableCell colSpan={6} align="center" sx={{py:5,color:'text.secondary'}}>No meetings in this range.</TableCell></TableRow>}</TableBody></Table></MainCard></>}
