import React,{useEffect,useMemo,useState} from 'react';
import {Alert,Box,Button,Card,CardContent,Chip,Grid,Stack,TextField,Typography} from '@mui/material';
import {RefreshOutlined,LocationOnOutlined,PeopleOutline} from '@mui/icons-material';
import dayjs from 'dayjs';
import api,{errorMessage} from '../../api/client';
import PageHeader from '../../components/PageHeader';import StatusBadge from '../../components/StatusBadge';import {fmtTime} from '../../utils/date';
export default function BookingCalendarPage(){const [from,setFrom]=useState(dayjs().format('YYYY-MM-DD'));const [rows,setRows]=useState([]);const [error,setError]=useState('');
 const to=useMemo(()=>dayjs(from).add(6,'day').format('YYYY-MM-DD'),[from]);const load=async()=>{try{setRows((await api.get('/bookings/calendar/range',{params:{from,to}})).data);setError('')}catch(e){setError(errorMessage(e))}};useEffect(()=>{load()},[from]);
 const days=useMemo(()=>Array.from({length:7},(_,i)=>dayjs(from).add(i,'day')),[from]);
 return <><PageHeader title="Booking Calendar" subtitle="Weekly view of approved meetings. Admin also sees pending requests." action={<Stack direction="row" spacing={1}><TextField size="small" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><Button startIcon={<RefreshOutlined/>} onClick={load}>Refresh</Button></Stack>}/>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}<Grid container spacing={1.5}>{days.map(d=>{const list=rows.filter(b=>dayjs(b.startAt).format('YYYY-MM-DD')===d.format('YYYY-MM-DD'));return <Grid item xs={12} md={6} xl key={d.format()}><Card sx={{height:'100%',minHeight:330}}><CardContent><Box sx={{pb:1.5,mb:1.5,borderBottom:'1px solid #edf2f7'}}><Typography fontWeight={800}>{d.format('ddd')}</Typography><Typography color="text.secondary" fontSize={13}>{d.format('DD/MM/YYYY')}</Typography></Box><Stack spacing={1.2}>{list.map(b=><Box key={b.id} sx={{p:1.4,border:'1px solid #e8edf3',borderRadius:2,bgcolor:'#fbfdff'}}><Box sx={{display:'flex',justifyContent:'space-between',gap:1}}><Typography fontWeight={700} fontSize={14}>{b.title}</Typography><StatusBadge status={b.status}/></Box><Typography color="primary.main" fontWeight={700} fontSize={13} sx={{mt:.8}}>{fmtTime(b.startAt)} - {fmtTime(b.endAt)}</Typography><Typography variant="caption" color="text.secondary" sx={{display:'flex',alignItems:'center',gap:.5,mt:.6}}><LocationOnOutlined sx={{fontSize:15}}/>{b.room.name}</Typography><Typography variant="caption" color="text.secondary" sx={{display:'flex',alignItems:'center',gap:.5}}><PeopleOutline sx={{fontSize:15}}/>{b.attendeeCount} · {b.createdBy.fullName}</Typography></Box>)}{list.length===0&&<Chip label="No meeting" size="small" variant="outlined"/>}</Stack></CardContent></Card></Grid>})}</Grid></>}
