import React,{useEffect,useState} from 'react';
import {Alert,Button,Dialog,DialogActions,DialogContent,DialogTitle,Stack,Table,TableBody,TableCell,TableContainer,TableHead,TableRow,TextField,Typography} from '@mui/material';
import {CheckCircleOutline,CloseOutlined,RefreshOutlined} from '@mui/icons-material';
import api,{errorMessage} from '../../api/client';
import PageHeader from '../../components/PageHeader';import MainCard from '../../components/MainCard';import StatusBadge from '../../components/StatusBadge';import {fmtDateTime} from '../../utils/date';
export default function ApprovalPage(){const [rows,setRows]=useState([]);const [error,setError]=useState('');const [reject,setReject]=useState(null);const [reason,setReason]=useState('');const [busy,setBusy]=useState(null);
 const load=async()=>{try{setRows((await api.get('/admin/bookings/pending')).data);setError('')}catch(e){setError(errorMessage(e))}};useEffect(()=>{load()},[]);
 const approve=async id=>{setBusy(id);try{await api.patch(`/admin/bookings/${id}/approve`);load()}catch(e){setError(errorMessage(e))}finally{setBusy(null)}};
 const doReject=async()=>{if(!reason.trim())return;setBusy(reject.id);try{await api.patch(`/admin/bookings/${reject.id}/reject`,{reason});setReject(null);setReason('');load()}catch(e){setError(errorMessage(e))}finally{setBusy(null)}};
 return <><PageHeader title="Booking Approvals" subtitle="Approve only after reviewing room, time and attendee details." action={<Button startIcon={<RefreshOutlined/>} onClick={load}>Refresh</Button>}/>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}<MainCard><TableContainer><Table><TableHead><TableRow><TableCell align="center">No.</TableCell><TableCell>Request</TableCell><TableCell>Room</TableCell><TableCell>Requester</TableCell><TableCell>Time</TableCell><TableCell>People</TableCell><TableCell>Status</TableCell><TableCell align="right">Decision</TableCell></TableRow></TableHead><TableBody>{rows.map((b,index)=><TableRow key={b.id} hover><TableCell align="center">{index+1}</TableCell><TableCell><Typography fontWeight={700}>{b.title}</Typography><Typography variant="caption" color="text.secondary">{b.purpose||'No purpose provided'}</Typography></TableCell><TableCell>{b.room.code}<br/><Typography variant="caption">{b.room.name}</Typography></TableCell><TableCell>{b.createdBy.fullName}<br/><Typography variant="caption">{b.createdBy.username}</Typography></TableCell><TableCell>{fmtDateTime(b.startAt)}<br/><Typography variant="caption">to {fmtDateTime(b.endAt)}</Typography></TableCell><TableCell>{b.attendeeCount} / {b.room.capacity}</TableCell><TableCell><StatusBadge status={b.status}/></TableCell><TableCell align="right"><Stack direction="row" spacing={1} justifyContent="flex-end"><Button size="small" variant="contained" color="success" startIcon={<CheckCircleOutline/>} disabled={busy===b.id} onClick={()=>approve(b.id)}>Approve</Button><Button size="small" color="error" startIcon={<CloseOutlined/>} onClick={()=>{setReject(b);setReason('')}}>Reject</Button></Stack></TableCell></TableRow>)}{rows.length===0&&<TableRow><TableCell colSpan={8} align="center" sx={{py:6,color:'text.secondary'}}>No pending requests.</TableCell></TableRow>}</TableBody></Table></TableContainer></MainCard>
 <Dialog open={Boolean(reject)} onClose={()=>setReject(null)} fullWidth maxWidth="xs"><DialogTitle>Reject booking</DialogTitle><DialogContent><Typography sx={{mb:2}}>Provide a reason for <b>{reject?.title}</b>.</Typography><TextField autoFocus fullWidth multiline minRows={3} label="Reject reason" value={reason} onChange={e=>setReason(e.target.value)}/></DialogContent><DialogActions><Button onClick={()=>setReject(null)}>Cancel</Button><Button color="error" variant="contained" disabled={!reason.trim()||busy===reject?.id} onClick={doReject}>Reject</Button></DialogActions></Dialog></>}
