import React,{useEffect,useState} from 'react';
import {Alert,Button,Dialog,DialogActions,DialogContent,DialogTitle,Grid,IconButton,MenuItem,Table,TableBody,TableCell,TableContainer,TableHead,TableRow,TextField,Tooltip,Typography} from '@mui/material';
import {AddOutlined,DeleteOutline,EditOutlined,RefreshOutlined} from '@mui/icons-material';
import api,{errorMessage} from '../../api/client';
import PageHeader from '../../components/PageHeader';import MainCard from '../../components/MainCard';import StatusBadge from '../../components/StatusBadge';
const empty={code:'',name:'',location:'',capacity:8,description:'',amenities:'',status:'AVAILABLE'};
export default function RoomManagementPage(){const [rows,setRows]=useState([]);const [editing,setEditing]=useState(undefined);const [form,setForm]=useState(empty);const [error,setError]=useState('');const [saving,setSaving]=useState(false);
 const load=async()=>{try{setRows((await api.get('/rooms')).data);setError('')}catch(e){setError(errorMessage(e))}};useEffect(()=>{load()},[]);
 const openCreate=()=>{setEditing(null);setForm(empty)};const openEdit=r=>{setEditing(r);setForm({...r})};const close=()=>setEditing(undefined);
 const save=async()=>{setSaving(true);setError('');try{const payload={...form,capacity:Number(form.capacity)};if(editing)await api.put(`/rooms/${editing.id}`,payload);else await api.post('/rooms',payload);close();load()}catch(e){setError(errorMessage(e))}finally{setSaving(false)}};
 const del=async r=>{if(!window.confirm(`Delete ${r.name}? Used rooms cannot be deleted.`))return;try{await api.delete(`/rooms/${r.id}`);load()}catch(e){setError(errorMessage(e))}};
 return <><PageHeader title="Room Management" subtitle="Create rooms and control availability / maintenance status." action={<Button variant="contained" startIcon={<AddOutlined/>} onClick={openCreate}>Add room</Button>}/>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}<MainCard secondary={<Button startIcon={<RefreshOutlined/>} onClick={load}>Refresh</Button>}><TableContainer><Table><TableHead><TableRow><TableCell align="center">No.</TableCell><TableCell>Code</TableCell><TableCell>Room</TableCell><TableCell>Location</TableCell><TableCell>Capacity</TableCell><TableCell>Amenities</TableCell><TableCell>Status</TableCell><TableCell align="right">Actions</TableCell></TableRow></TableHead><TableBody>{rows.map((r,index)=><TableRow key={r.id} hover><TableCell align="center">{index+1}</TableCell><TableCell><Typography fontWeight={700}>{r.code}</Typography></TableCell><TableCell>{r.name}</TableCell><TableCell>{r.location}</TableCell><TableCell>{r.capacity}</TableCell><TableCell sx={{maxWidth:300}}>{r.amenities||'-'}</TableCell><TableCell><StatusBadge status={r.status}/></TableCell><TableCell align="right"><Tooltip title="Edit"><IconButton onClick={()=>openEdit(r)}><EditOutlined fontSize="small"/></IconButton></Tooltip><Tooltip title="Delete"><IconButton color="error" onClick={()=>del(r)}><DeleteOutline fontSize="small"/></IconButton></Tooltip></TableCell></TableRow>)}</TableBody></Table></TableContainer></MainCard>
 <Dialog open={editing!==undefined} onClose={close} fullWidth maxWidth="sm"><DialogTitle>{editing?'Edit room':'Add room'}</DialogTitle><DialogContent dividers><Grid container spacing={2}><Grid item xs={12} sm={4}><TextField fullWidth label="Room code" value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/></Grid><Grid item xs={12} sm={8}><TextField fullWidth label="Room name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Grid><Grid item xs={12} sm={8}><TextField fullWidth label="Location" value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></Grid><Grid item xs={12} sm={4}><TextField fullWidth type="number" label="Capacity" value={form.capacity} onChange={e=>setForm({...form,capacity:e.target.value})}/></Grid><Grid item xs={12}><TextField fullWidth label="Amenities (comma separated)" value={form.amenities||''} onChange={e=>setForm({...form,amenities:e.target.value})}/></Grid><Grid item xs={12}><TextField fullWidth multiline minRows={2} label="Description" value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></Grid><Grid item xs={12}><TextField select fullWidth label="Status" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{['AVAILABLE','MAINTENANCE','DISABLED'].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField></Grid></Grid></DialogContent><DialogActions><Button onClick={close}>Cancel</Button><Button variant="contained" onClick={save} disabled={saving||!form.code||!form.name||!form.location}>{saving?'Saving...':'Save'}</Button></DialogActions></Dialog></>}
