import React,{useEffect,useState} from 'react';
import {Alert,Button,Dialog,DialogActions,DialogContent,DialogTitle,Grid,MenuItem,Switch,Table,TableBody,TableCell,TableContainer,TableHead,TableRow,TextField,Typography} from '@mui/material';
import {AddOutlined,RefreshOutlined} from '@mui/icons-material';
import api,{errorMessage} from '../../api/client';
import {useAuth} from '../../auth/AuthContext';import PageHeader from '../../components/PageHeader';import MainCard from '../../components/MainCard';
const empty={username:'',email:'',fullName:'',password:'',role:'USER'};
export default function UserManagementPage(){const {user}=useAuth();const [rows,setRows]=useState([]);const [open,setOpen]=useState(false);const [form,setForm]=useState(empty);const [error,setError]=useState('');const [saving,setSaving]=useState(false);
 const load=async()=>{try{setRows((await api.get('/admin/users')).data);setError('')}catch(e){setError(errorMessage(e))}};useEffect(()=>{load()},[]);
 const create=async()=>{setSaving(true);try{await api.post('/admin/users',form);setOpen(false);setForm(empty);load()}catch(e){setError(errorMessage(e))}finally{setSaving(false)}};
 const toggle=async u=>{try{await api.patch(`/admin/users/${u.id}/enabled`,{enabled:!u.enabled});load()}catch(e){setError(errorMessage(e))}};
 return <><PageHeader title="User Management" subtitle="Create users, assign roles and enable/disable access." action={<Button variant="contained" startIcon={<AddOutlined/>} onClick={()=>setOpen(true)}>Add user</Button>}/>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}<MainCard secondary={<Button startIcon={<RefreshOutlined/>} onClick={load}>Refresh</Button>}><TableContainer><Table><TableHead><TableRow><TableCell align="center">No.</TableCell><TableCell>User</TableCell><TableCell>Email</TableCell><TableCell>Full name</TableCell><TableCell>Role</TableCell><TableCell>Enabled</TableCell></TableRow></TableHead><TableBody>{rows.map((u,index)=><TableRow key={u.id}><TableCell align="center">{index+1}</TableCell><TableCell><Typography fontWeight={700}>{u.username}</Typography></TableCell><TableCell>{u.email}</TableCell><TableCell>{u.fullName}</TableCell><TableCell>{u.role}</TableCell><TableCell><Switch checked={u.enabled} disabled={u.id===user?.id} onChange={()=>toggle(u)}/></TableCell></TableRow>)}</TableBody></Table></TableContainer></MainCard>
 <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Add user</DialogTitle><DialogContent dividers><Grid container spacing={2}><Grid item xs={12} sm={6}><TextField fullWidth label="Username" value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></Grid><Grid item xs={12} sm={6}><TextField fullWidth label="Full name" value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/></Grid><Grid item xs={12}><TextField fullWidth type="email" label="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Grid><Grid item xs={12} sm={8}><TextField fullWidth type="password" label="Initial password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></Grid><Grid item xs={12} sm={4}><TextField select fullWidth label="Role" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><MenuItem value="USER">USER</MenuItem><MenuItem value="ADMIN">ADMIN</MenuItem></TextField></Grid></Grid></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancel</Button><Button variant="contained" disabled={saving||!form.username||!form.email||!form.fullName||form.password.length<6} onClick={create}>{saving?'Creating...':'Create user'}</Button></DialogActions></Dialog></>}
